import Head from "next/head";
import Link from "next/link";

// component
import Header from "./component/header/header";
import MainSwiper from "./component/main-swiper/main-swiper";
import Layout from "./component/layout/layout";
import Footer from "./component/footer/footer";

// pages
import Home from "./home/home";
import styles from "../styles/app.module.css";

// import { Inter } from "@next/font/google";
// const inter = Inter({ subsets: ["latin"] });

interface JobInterface<T> {
  map(arg0: (post: any) => void): import("react").ReactNode;
  data: any;
  [key: number]: T;
}

export async function getStaticProps() {
  // const baseURL = "http://localhost:3000";
  // const res = await fetch("/testJson/job.json");
  // const data = await res.json();

  const data = [
    { id: 1, title: "공지사항 타이틀입니다.1", date: "2022-12-23" },
    { id: 2, title: "공지사항 타이틀입니다.2", date: "2023-01-02" },
    { id: 3, title: "공지사항 타이틀입니다.3", date: "2023-01-04" },
    { id: 4, title: "공지사항 타이틀입니다.4", date: "2023-01-06" },
    { id: 5, title: "공지사항 타이틀입니다.5", date: "2023-01-07" },
    { id: 6, title: "공지사항 타이틀입니다.6", date: "2023-03-02" },
    { id: 7, title: "공지사항 타이틀입니다.7", date: "2023-01-09" },
    { id: 8, title: "공지사항 타이틀입니다.8", date: "2023-01-12" },
  ];
  return {
    props: {
      allPostsData: data,
    },
  };
}

export default function App({ allPostsData }: { allPostsData: JobInterface<number> }) {
  const mappingArray = allPostsData;

  let test: any = chunk(mappingArray, 4);
  // console.log(test);

  return (
    <>
      <Head>
        <title>MapleStory</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <MainSwiper />
        <Layout>
          <Home />
        </Layout>
        <section className={styles.section02}>
          <Layout>
            <p className={styles.sectionTitle}>메이플스토리 공지사항</p>
            <ul>
              <li>
                {test[0].map((item: any, i: number) => {
                  return (
                    <div className={styles.item} key={item.id}>
                      <Link href={`/notice/${item.id}`}>{item.title}</Link>
                      <span>{item.date}</span>
                    </div>
                  );
                })}
              </li>
              <li>
                {test[1].map((item: any, i: number) => {
                  return (
                    <div className={styles.item} key={item.id}>
                      <Link href={`/notice/${item.id}`}>{item.title}</Link>
                      <span>{item.date}</span>
                    </div>
                  );
                })}
              </li>
            </ul>
          </Layout>
        </section>
        <Footer />
      </main>
    </>
  );
}

function chunk(data: any, size = 1): object {
  const arr = [];

  for (let i = 0; i < data.length; i += size) {
    arr.push(data.slice(i, i + size));
  }
  return arr;
}
